server:
  port: 8080 # Or any port you prefer for the gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to the user-service
        - id: user-service-route
          uri: lb://user-service # "lb" stands for load-balanced, using the service ID from Eureka
          predicates:
            - Path=/api/v1/users/** # Match any request to /api/v1/users/...

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost